---
- name: "nxos.backup: fetch network configuration"
  nxos_config:
    backup: "true"
  register: r_nxos_config

- name: "nxos.backup: remove non configuration lines"
  changed_when: false
  lineinfile:
    path: "{{ r_nxos_config.backup_path }}"
    regexp: "{{ item }}"
    state: "absent"
  loop:
    - '^(Current|Building) configuration.*'
    - '^\!.*'

- name: "nxos.backup: save configuration to git_store"
  copy:
    src: "{{ r_nxos_config.backup_path }}"
    dest: "{{ git_store }}/{{ backup_manager_backup_path }}/running.cfg"
    force: "yes"
  notify: git_sync
