---
- name: "fortios.restore: load configuration"
  environment:
    PYTHONHTTPSVERIFY: 0
  fortios_config:
    host: "{{ __backup_manager_provider.host }}"
    username: "{{ __backup_manager_provider.username }}"
    password: "{{ __backup_manager_provider.password }}"
    https: "{{ __backup_manager_provider.https }}"
    vdom: "{{ __backup_manager_provider.vdom }}"
    src: "{{ git_store }}/{{ backup_manager_backup_path }}/running.cfg"
