---
git_url: 'git@github.com:redhatautomation/network_sot.git'
git_key: "{{ lookup('file','~/.ssh/gdykeman.pem') }}"
git_branch: 'master'
git_msg: 'update files with ansible'
git_remove_local: false
git_username: ansible_git
git_email: ansible_git@ansible.com 